hooks
style
 ^'
li
{
margin: 5px 0;
}
#inputs input {
	font-size: 14px;
	border: 1px solid #ccc;
	border-radius: 3px;
	box-shadow: 0 1px 1px #ccc inset, 0 1px 0 #fff;
	font-family: Chivo, Verdana, arial, sans-serif;
	text-align:center;
}

.textInputDisabled{
	background: #f1f1f1;
}

#inputs div {
    margin: 8px 0;
}


#IdStreet, #nameList {
	width: 100%;
	box-sizing: border-box;
}

#IdRetardo {
	width: 12%;

}

#IdLimiteHs {
	width: 10%;

}

#IdLimiteMin {
	width: 10%;

}

.button{
    background-color: #ffb94b;
    background-image: -webkit-gradient(linear, left top, left bottom, from(#fddb6f), to(#ffb94b));
    background-image: -webkit-linear-gradient(top, #fddb6f, #ffb94b);
    background-image: -moz-linear-gradient(top, #fddb6f, #ffb94b);
    background-image: -ms-linear-gradient(top, #fddb6f, #ffb94b);
    background-image: -o-linear-gradient(top, #fddb6f, #ffb94b);
    background-image: linear-gradient(top, #fddb6f, #ffb94b);
    border-radius: 3px;
    text-shadow: 0 1px 0 rgba(255,255,255,0.5);
    box-shadow: 0 0 1px rgba(0, 0, 0, 0.3), 0 1px 0 rgba(255, 255, 255, 0.3) inset;    
    border-width: 1px;
    border-style: solid;
    border-color: #d69e31 #e3a037 #d5982d #e3a037;
    height: 35px;
    padding: 0;
    width:100%;
    cursor: pointer;
    font: bold 15px Arial, Helvetica;
    color: #8f5a0a;
}

.button:hover, .button:focus
{		
    background-color: #fddb6f;
    background-image: -webkit-gradient(linear, left top, left bottom, from(#ffb94b), to(#fddb6f));
    background-image: -webkit-linear-gradient(top, #ffb94b, #fddb6f);
    background-image: -moz-linear-gradient(top, #ffb94b, #fddb6f);
    background-image: -ms-linear-gradient(top, #ffb94b, #fddb6f);
    background-image: -o-linear-gradient(top, #ffb94b, #fddb6f);
    background-image: linear-gradient(top, #ffb94b, #fddb6f);
}	
	
	
.buttonSilver{
    background-color: #CACACA;
    background-image: -webkit-gradient(linear, left top, left bottom, from(#EBEBEB), to(#CACACA));
    background-image: -webkit-linear-gradient(top, #EBEBEB, #CACACA);
    background-image: -moz-linear-gradient(top, #EBEBEB, #CACACA);
    background-image: -ms-linear-gradient(top, #EBEBEB, #CACACA);
    background-image: -o-linear-gradient(top, #EBEBEB, #CACACA);
    background-image: linear-gradient(top, #EBEBEB, #CACACA);
    border-radius: 3px;
    text-shadow: 0 1px 0 rgba(255,255,255,0.5);
    box-shadow: 0 0 1px rgba(0, 0, 0, 0.3), 0 1px 0 rgba(255, 255, 255, 0.3) inset;    
    border-width: 1px;
    border-style: solid;
    height: 35px;
    padding: 0;
    width:100%;
    cursor: pointer;
    font: bold 15px Arial, Helvetica;
    color: #797979;
}

.buttonSilver:hover, .buttonSilver:focus
{		
    background-color: #CACACA;
    background-image: -webkit-gradient(linear, left top, left bottom, from(#CACACA), to(#EBEBEB));
    background-image: -webkit-linear-gradient(top, #CACACA, #EBEBEB);
    background-image: -moz-linear-gradient(top, #CACACA, #EBEBEB);
    background-image: -ms-linear-gradient(top, #CACACA, #EBEBEB);
    background-image: -o-linear-gradient(top, #CACACA, #EBEBEB);
    background-image: linear-gradient(top, #CACACA, #EBEBEB);
}	
	
.removeButton
{
color: white;
background-color: #BEBEBE;
border-radius: 55px;
border: 0;
box-shadow: 0px 0px 3px black;
height: 10px;
width: 10px;
margin-right: 7px;
cursor: pointer;
}

.removeButton:hover
{
background-color: #F75454;
}

.titleBoxbutton {
float: right;
width: 100px;
margin-top: 10px;
height: 25px;
cursor: pointer;
background: #F3F3F3;
border: solid 1px #D9D9D9;
border-radius: 3px;
text-shadow: 0 1px 0 white;
color: #7A7A7A;
box-shadow: 1px 1px 1px white;
}

.titleBoxbutton:hover {
	background: green;
	color: white;
	text-shadow: 0 1px 0 black;
	border: solid 1px #A8A8A8;
}

.titleBox {
display: inline-block;
}

'